name: build-pr

on:
  pull_request:
    branches: main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    env:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: cp .npmrc.example .npmrc
      - run: npm ci
      - run: npm run build --if-present
      # - run: npm test
      # - run: npm run test:e2e
